version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest # Use the desired Node.js version

  pre_build:
    commands:
      - cd frontend # Change directory to 'frontend'
      - npm install # Install project dependencies

  build:
    commands:
      - npm run build # Run the npm build command (output will go to 'dist' inside 'frontend')

  post_build:
    commands:
      - aws s3 sync dist/ s3://okcrentals-dev/
