version: 0.2

phases:
  install:
    runtime-versions:
      java: latest
    commands:
      - echo "Ensure docker is running..."
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  pre_build:
    commands:
      - export MY_VERSION=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 830433532063.dkr.ecr.us-east-2.amazonaws.com

  build:
    commands:
      - echo "Building the Docker image..."
      - ./gradlew bootBuildImage --imageName=830433532063.dkr.ecr.us-east-2.amazonaws.com/carrentals:${MY_VERSION}
      - ./gradlew bootBuildImage --imageName=830433532063.dkr.ecr.us-east-2.amazonaws.com/carrentals:latest


  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push 830433532063.dkr.ecr.us-east-2.amazonaws.com/carrentals:${MY_VERSION}
      - docker push 830433532063.dkr.ecr.us-east-2.amazonaws.com/carrentals:latest

artifacts:
  files:
    - '**/*'
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'
