services:
  mysql:
    image: 'mysql:8.0'
    environment:
      - MYSQL_ROOT_HOSTS=%
      - MYSQL_DATABASE=spring_boot_mysql
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - "3306:3306"
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
