aws:
  region: us-east-2
  s3:
    bucket: carrentaluserfiles

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/car_rentals
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: false
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  devtools:
    restart:
      enabled: true
      poll-interval: 5s
      additional-paths: static/stc


comms:
  twilio:
    auth-token: 4896a602e99673000780ac4d661cbf73
    sid: ACeeaa2e225cdfedd522e6fe26528a1ee5
    service: VAc3960f6b1aa900f290d66e04b5273ce3
    debug: true

stripe:
  secret-key: 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
  secret-key-test: sk_test_51NPTGWHa21OTRYKEKdmY1MaHU7Es1Zt6KP3HFuUysNyiRzkYxIWH2cvJlD1X1P78JZBf3YQ0Mn205mHWW38kOZVA00jxVN3SaT
  webhook-secret: whsec_4fddc0db0054eec2c80a86c6b745622c64744e6606c6239a2b9978a07584bcb3
  checkout-url-success: http://localhost:3000/checkout-success
  checkout-url-cancel: http://localhost:3000/checkout-cancel


## Circuit Breaker

resilience4j:
  circuitbreaker:
    configs:
      default:
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
    instances:
      twilioVerifyApi:
        baseConfig: default
      twilioStartVerificationApi:
        baseConfig: default

  ratelimiter:
    configs:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0s
    instances:
      twilioVerifyApi:
        baseConfig: default
      twilioStartVerificationApi:
        baseConfig: default

  retry:
    configs:
      default:
        max-attempts: 3
        waitDuration: 2s
    instances:
      twilioVerifyApi:
        baseConfig: default
      twilioStartVerificationApi:
        baseConfig: default

  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 20
        maxWaitDuration: 500ms
    instances:
      twilioVerifyApi:
        baseConfig: default
      twilioStartVerificationApi:
        baseConfig: default
# ------